// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb7zl6Y7NrX5c8wpvKmTDEd-0r4T7xmIc',
    appId: '1:204632288660:web:90268485a3f560a8bff381',
    messagingSenderId: '204632288660',
    projectId: 'salonhub-cb808',
    authDomain: 'salonhub-cb808.firebaseapp.com',
    storageBucket: 'salonhub-cb808.appspot.com',
    measurementId: 'G-ZNLBTFMG9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUVie8ADH8m1YqZ8Wnjjx0xik5QHuJeI',
    appId: '1:204632288660:android:70d1287d34ee5a3dbff381',
    messagingSenderId: '204632288660',
    projectId: 'salonhub-cb808',
    storageBucket: 'salonhub-cb808.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd2qKyE92QFCkNaZIfSJ5gxykPcMCkDGs',
    appId: '1:204632288660:ios:d1a8df4986f20482bff381',
    messagingSenderId: '204632288660',
    projectId: 'salonhub-cb808',
    storageBucket: 'salonhub-cb808.appspot.com',
    iosBundleId: 'com.example.salonHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd2qKyE92QFCkNaZIfSJ5gxykPcMCkDGs',
    appId: '1:204632288660:ios:d1a8df4986f20482bff381',
    messagingSenderId: '204632288660',
    projectId: 'salonhub-cb808',
    storageBucket: 'salonhub-cb808.appspot.com',
    iosBundleId: 'com.example.salonHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb7zl6Y7NrX5c8wpvKmTDEd-0r4T7xmIc',
    appId: '1:204632288660:web:852b00dc6af9d26bbff381',
    messagingSenderId: '204632288660',
    projectId: 'salonhub-cb808',
    authDomain: 'salonhub-cb808.firebaseapp.com',
    storageBucket: 'salonhub-cb808.appspot.com',
    measurementId: 'G-MXV7C1RM6V',
  );

}